name: Generate pacman animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: copy pacman-contribution-graph.svg as pacman-contribution-graph-dark.svg and cambiar colores
        run: |
          cp dist/pacman-contribution-graph.svg dist/pacman-contribution-graph-dark.svg
          sed -i 's/#fff/#181818/g; s/#ffffff/#181818/g; s/#000/#fff/g; s/#000000/#fff/g' dist/pacman-contribution-graph-dark.svg

      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
