name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pacman SVG
        uses: Platane/snk@v3
        with:
          github_user_name: seojcarlos
          outputs: |
            dist/pacman-contribution-graph.svg

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
